In [ ]:
import pandas as pd

In [4]:
df = pd.read_parquet('../assets/sample.parquet')

In [6]:
df

,email,name,gender,created_at,last_visited_at,last_watched_at,recent_watched,viewed_but_not_started,started_but_not_finished,finished,last_email_notification,last_in_app_notification,last_sms_notification
0,abbigail.i2arj4zn@example.net,何瀚福,unknown,1561828503,1719468723,1718863983,"[120675, 149258, 114415, 186403, 176228, 197737]","[235689, 246545, 265809, 290168, 203355, 23874...","[378574, 379648, 364897]","[453425, 422981, 454390, 440272, 412486, 40717...",1718399463,1719395163,1712799063
1,abdul.6d92e6bs@example.org,冯娜盈,unknown,1561899573,1718932353,1712617473,"[125866, 103868, 142816, 175142, 119182, 10213...","[232396, 236798, 295531]","[335985, 357036, 340775, 398372, 300246, 33689...","[435181, 463343]",1716033813,1719337653,1712324073
2,abdul.c24lxfwi@example.net,杨语凤,unknown,1561808454,1717233294,1713239274,"[136972, 106211, 179890, 178407, 103121, 14531...","[298319, 230161, 243761, 210045, 273102, 24712...","[317367, 377385, 386924, 377828, 359363, 38520...","[416882, 437822, 400447, 471879, 445391, 44545...",1718505654,1719152334,1714336194
3,abdullah.1pv6ugtr@example.net,吕雨珍,unknown,1561891044,1717046484,1718466504,"[102783, 119836, 125671, 109900, 115919, 13659...","[247605, 286331, 237213, 296813, 277906, 27762...","[353475, 308669, 351208, 391888, 362686, 32437...","[499945, 417318, 434799, 473662, 463038, 42776...",1717926084,1719294084,1717713924
4,abel.76b5fr5i@example.com,陈雅儿,unknown,1561884685,1718600545,1718056225,"[127656, 157605, 191001, 173353, 110464, 19230...","[216329, 265683, 282150, 298684, 244270, 23839...","[367875, 319296, 357132, 332589, 301509, 32065...","[433333, 468615, 495258, 421994, 407564, 47060...",1718365045,1718483005,1718310865
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,reyna.qn2g5j96@example.org,谭秋风,unknown,1561924794,1717643394,1712111634,"[199732, 192807, 165026, 158565, 145929, 17202...",[],"[388310, 363256, 321074, 301234, 374089, 34758...","[418179, 498195, 438003, 408133, 467391, 40285...",1718122074,1718848194,1717030314
996,rhett.mwnipq0l@example.com,邱任平,unknown,1561860273,1719037533,1718261913,"[146902, 104163, 140920, 160896, 160775, 16300...","[271489, 288802, 224535, 276638, 215493, 26291...","[369692, 351207, 317844, 391635, 397366, 37068...","[421399, 497689, 471171, 421875, 463226, 47202...",1718965533,1718904633,1717469013
997,richmond.syk4rmp4@example.com,张鼎遥,unknown,1561899094,1717149094,1714032574,"[136726, 141143, 128130, 188001, 191861, 11178...","[251221, 209636, 277312, 248235, 281099, 22240...","[310030, 366503, 360302, 314242, 321831, 31803...","[484443, 477008, 436435, 441560, 491200, 44293...",1717883914,1718797594,1711910494
998,rickie.2eprv9va@example.com,付寒云,unknown,1561926677,1718831597,1716997157,"[101510, 182508, 109751, 119666, 168185, 18980...","[263366, 227250, 228135, 291408, 233564, 22691...","[365707, 357256, 389516, 307430, 328090, 38660...","[465632, 427515, 496342, 452325, 427867, 49149...",1716882497,1719397757,1713198557
999,rita.hs7ufnr9@example.org,邓鼎宇,unknown,1561932203,1717055843,1713886463,"[105315, 126790, 122988, 140660, 134216, 10281...","[224253, 281995, 229314, 288938, 215194, 23068...","[305263, 386501, 355816, 391960, 364719, 39047...","[478413, 451240, 464513, 416817, 496053, 44819...",1718769203,1719390503,1713700403

In [7]:
df.describe()

,created_at,last_visited_at,last_watched_at,last_email_notification,last_in_app_notification,last_sms_notification
count,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03
mean,1.561854e+09,1.718182e+09,1.715551e+09,1.717596e+09,1.718835e+09,1.715605e+09
std,4.923691e+04,7.497247e+05,2.265033e+06,1.129392e+06,3.625031e+05,2.224445e+06
min,1.561772e+09,1.716895e+09,1.711714e+09,1.715606e+09,1.718184e+09,1.711708e+09
25%,1.561811e+09,1.717550e+09,1.713627e+09,1.716602e+09,1.718518e+09,1.713735e+09
50%,1.561853e+09,1.718182e+09,1.715511e+09,1.717611e+09,1.718848e+09,1.715562e+09
75%,1.561897e+09,1.718814e+09,1.717578e+09,1.718580e+09,1.719156e+09,1.717458e+09
max,1.561939e+09,1.719480e+09,1.719428e+09,1.719460e+09,1.719475e+09,1.719479e+09

In [14]:
df[df['created_at'].dtype >= '2024-01-25']

TypeError: Invalid comparison between dtype=uint32 and str